services:
   # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=aibot
    volumes:
      - mongodb_data:/data/db
    networks:
      - sdn_network

  # Qdrant (Vector DB)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant1
    restart: always
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    expose:
      - "6333"
      - "6334"
      - "6335"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - sdn_network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sdn_network
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight-data:/data
    networks:
      - sdn_network

networks:
  sdn_network:
    driver: bridge

volumes:
  redis-data:
  redisinsight-data:
  mongodb_data:
  qdrant_data: