services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file: .env
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: ../backend/.env.dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
 
networks:
  app_network:
    name: sdn_network
    external: true

